import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'StackSprinter App',
  description: 'Generated by StackSprinter - Next.js + Supabase + Vercel',
  keywords: ['nextjs', 'supabase', 'vercel', 'stacksprinter'],
  authors: [{ name: 'StackSprinter' }],
  creator: 'StackSprinter',
  openGraph: {
    type: 'website',
    locale: 'en_US',
    title: 'StackSprinter App',
    description: 'Generated by StackSprinter - Next.js + Supabase + Vercel',
    siteName: 'StackSprinter App',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'StackSprinter App',
    description: 'Generated by StackSprinter - Next.js + Supabase + Vercel',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100">
          {children}
        </div>
      </body>
    </html>
  );
}