import { execCommand } from './exec.js';
import { log, LogLevel } from './log.js';
import { initGitRepo, ensureGitConfig, addAllFiles, createCommit, addRemote, pushToRemote, createGitignore } from './git.js';

export interface GitHubRepoInfo {
  url: string;
  sshUrl: string;
  cloneUrl: string;
  name: string;
  fullName: string;
  owner: string;
}

export async function getGitHubUser(): Promise<string> {
  try {
    const result = await execCommand('gh api user --jq .login', { silent: true });
    return result.trim();
  } catch {
    // Fallback to git config if gh fails
    try {
      const email = await execCommand('git config --global user.email', { silent: true });
      // Extract username from email (basic heuristic)
      const username = email.split('@')[0];
      return username || 'user';
    } catch {
      return 'user';
    }
  }
}

export async function checkGitHubAuth(): Promise<boolean> {
  try {
    await execCommand('gh auth status', { silent: true });
    return true;
  } catch {
    return false;
  }
}

export async function loginToGitHub(): Promise<void> {
  const isAuthed = await checkGitHubAuth();
  
  if (!isAuthed) {
    log('Not authenticated with GitHub CLI', LogLevel.INFO);
    log('Please run "gh auth login" first, or set GH_TOKEN environment variable', LogLevel.INFO);
    process.exit(1);
  }
  
  log('GitHub authentication verified', LogLevel.DEBUG);
}

export async function createGitHubRepo(
  appName: string,
  org?: string,
  visibility: 'public' | 'private' = 'private'
): Promise<string> {
  await loginToGitHub();
  
  const owner = org || await getGitHubUser();
  const repoName = appName.toLowerCase().replace(/[^a-z0-9-]/g, '-');
  const fullName = `${owner}/${repoName}`;
  
  log(`Creating GitHub repository: ${fullName}`, LogLevel.DEBUG);
  
  try {
    // Check if repo already exists
    await execCommand(`gh repo view ${fullName}`, { silent: true });
    log(`Repository ${fullName} already exists`, LogLevel.DEBUG);
    return `https://github.com/${fullName}`;
  } catch {
    // Repo doesn't exist, create it
  }
  
  const createCmd = org 
    ? `gh repo create ${fullName} --${visibility} --description "Generated by StackSprinter"`
    : `gh repo create ${repoName} --${visibility} --description "Generated by StackSprinter"`;
    
  await execCommand(createCmd);
  
  const repoUrl = `https://github.com/${fullName}`;
  log(`Repository created: ${repoUrl}`, LogLevel.DEBUG);
  
  return repoUrl;
}

export async function pushToGitHub(projectPath: string, repoUrl: string): Promise<void> {
  await ensureGitConfig();
  await initGitRepo(projectPath);
  await createGitignore(projectPath);
  
  // Stage all files
  await addAllFiles(projectPath);
  
  // Create initial commit
  await createCommit(projectPath, 'Initial commit from StackSprinter');
  
  // Add remote and push
  await addRemote(projectPath, 'origin', repoUrl);
  await pushToRemote(projectPath);
  
  log(`Code pushed to ${repoUrl}`, LogLevel.DEBUG);
}

export async function setRepositorySettings(
  owner: string,
  repo: string,
  settings: {
    branchProtection?: boolean;
    deleteBranchOnMerge?: boolean;
    squashMerge?: boolean;
  }
): Promise<void> {
  const { branchProtection = true, deleteBranchOnMerge = true, squashMerge = true } = settings;
  
  try {
    // Update repository settings
    const repoSettings = {
      delete_branch_on_merge: deleteBranchOnMerge,
      allow_squash_merge: squashMerge,
      allow_merge_commit: false,
      allow_rebase_merge: false
    };
    
    await execCommand(
      `gh api repos/${owner}/${repo} --method PATCH --field delete_branch_on_merge=${deleteBranchOnMerge} --field allow_squash_merge=${squashMerge}`
    );
    
    log('Repository settings updated', LogLevel.DEBUG);
    
    if (branchProtection) {
      // Set up branch protection for main
      try {
        const protectionRules = {
          required_status_checks: null,
          enforce_admins: false,
          required_pull_request_reviews: {
            required_approving_review_count: 1,
            dismiss_stale_reviews: true
          },
          restrictions: null,
          allow_force_pushes: false,
          allow_deletions: false
        };
        
        await execCommand(
          `gh api repos/${owner}/${repo}/branches/main/protection --method PUT --input -`,
          { env: { INPUT: JSON.stringify(protectionRules) } }
        );
        
        log('Branch protection enabled for main', LogLevel.DEBUG);
      } catch (error) {
        log('Failed to set up branch protection (this is optional)', LogLevel.WARN);
      }
    }
  } catch (error) {
    log('Failed to update repository settings (this is optional)', LogLevel.WARN);
  }
}

export async function getRepositoryInfo(owner: string, repo: string): Promise<GitHubRepoInfo> {
  const result = await execCommand(`gh repo view ${owner}/${repo} --json url,sshUrl,cloneUrl,name,owner`);
  const data = JSON.parse(result);
  
  return {
    url: data.url,
    sshUrl: data.sshUrl,
    cloneUrl: data.cloneUrl,
    name: data.name,
    fullName: `${data.owner.login}/${data.name}`,
    owner: data.owner.login
  };
}

export async function createPullRequest(
  owner: string,
  repo: string,
  title: string,
  body: string,
  head: string,
  base: string = 'main'
): Promise<string> {
  const result = await execCommand(
    `gh pr create --repo ${owner}/${repo} --title "${title}" --body "${body}" --head ${head} --base ${base}`
  );
  
  // Extract PR URL from output
  const prUrl = result.match(/https:\/\/github\.com\/[^\s]+/)?.[0];
  if (!prUrl) {
    throw new Error('Failed to extract PR URL from GitHub CLI output');
  }
  
  return prUrl;
}

export async function listPullRequests(owner: string, repo: string, state: 'open' | 'closed' | 'all' = 'open'): Promise<any[]> {
  const result = await execCommand(`gh pr list --repo ${owner}/${repo} --state ${state} --json number,title,url,author`);
  return JSON.parse(result);
}

export async function isRepositoryEmpty(owner: string, repo: string): Promise<boolean> {
  try {
    await execCommand(`gh api repos/${owner}/${repo}/contents`, { silent: true });
    return false; // Has contents
  } catch (error) {
    if (error instanceof Error && error.message.includes('404')) {
      return true; // Empty repository
    }
    throw error;
  }
}